export const FETCH_EVENTS_START = 'FETCH_EVENTS_START'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE'

export const REMOVE_EVENT_START = 'REMOVE_EVENT_START'
export const REMOVE_EVENT_SUCCESS = 'REMOVE_EVENT_SUCCESS'
export const REMOVE_EVENT_FAILURE = 'REMOVE_EVENT_FAILURE'

export const CREATE_EVENT_START = 'CREATE_EVENT_START'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE'
export const ADD_EVENT = 'ADD_EVENT'
export const ADD_CREATED_EVENT_DATA = 'ADD_CREATED_EVENT_DATA'
